### ISSUE TITLE
the scripts doesn't work

### ISSUE THREAD

**Issue by wangmingg** [akatrevorjay/openwrt-masq6#2] opened 2017-03-07 15:17 UTC
I just set the configuration and the scripts doesn't work, it report:
nat6: Firewall config="cfg04dc81" zone="lan" zone_masq6="0".
nat6: Firewall config="cfg06dc81" zone="wan" zone_masq6="1".
nat6: Found firewall zone_name="wan" with zone_masq6="1" zone_masq6_privacy="0".
nat6: Setting up masquerading nat6 for zone_name="wan" with zone_masq6_privacy="                                                                                                             0"
nat6: Ensuring ip6tables chain="zone_wan_postrouting" contains our MASQUERADE.
ip6tables: No chain/target/match by that name.
root@OpenWrt:~#
besides,the resault of ip6tables -t -nat -vnL is:
root@OpenWrt:~# ip6tables -t nat -vnL
Chain PREROUTING (policy ACCEPT 5853 packets, 490K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 4071 packets, 344K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 790 packets, 109K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 790 packets, 109K bytes)
 pkts bytes target     prot opt in     out     source               destination
root@OpenWrt:~#
How can I solve the problem?

**Comment by akatrevorjay** [comment] 2017-03-07 22:59
Hi, this is a dupe of #1 , please watch that for updates. I posted a fix I'd like someone to try. Thanks!

**Closed as completed by akatrevorjay** 2017-03-07 22:59 UTC
Labels: duplicate
